#ifndef OPCODES_H
#define OPCODES_H

#include "common.h"

static const char *opcode_names[] = {
    "NOP",
    "ILL",
    "OUTL BUS, A",
    "ADD A, #data",
    "JMP (page 0)",
    "EN I",
    "ILL",
    "DEC A",
    "INS A, BUS",
    "IN A, P1",
    "IN A, P2",
    "ILL",
    "MOVD A, P4",
    "MOVD A, P5",
    "MOVD A, P6",
    "MOVD A, P7",
    "INC @R0",
    "INC @R1",
    "JB0",
    "ADDC A, #data",
    "CALL (page 0)",
    "DIS I",
    "JTF",
    "INC A",
    "INC R0",
    "INC R1",
    "INC R2",
    "INC R3",
    "INC R4",
    "INC R5",
    "INC R6",
    "INC R7",
    "XCH A, @R0",
    "XCH A, @R1",
    "ILL",
    "MOV A, #data",
    "JMP (page 1)",
    "EN TCNTI",
    "JNT0",
    "CLR A",
    "XCH A, R0",
    "XCH A, R1",
    "XCH A, R2",
    "XCH A, R3",
    "XCH A, R4",
    "XCH A, R5",
    "XCH A, R6",
    "XCH A, R7",
    "XCHD A, @R0",
    "XCHD A, @R1",
    "JB1",
    "ILL",
    "CALL (page 1)",
    "DIS TCNTI",
    "JT0",
    "CPL A",
    "ILL",
    "OUTL P1, A",
    "OUTL P2, A",
    "ILL",
    "MOVD P4, A",
    "MOVD P5, A",
    "MOVD P6, A",
    "MOVD P7, A",
    "ORL A, @R0",
    "ORL A, @R1",
    "MOV A, T",
    "ORL A, #data",
    "JMP (page 2)",
    "STRT CNT",
    "JNT1",
    "SWAP",
    "ORL A, R0",
    "ORL A, R1",
    "ORL A, R2",
    "ORL A, R3",
    "ORL A, R4",
    "ORL A, R5",
    "ORL A, R6",
    "ORL A, R7",
    "ANL A, @R0",
    "ANL A, @R1",
    "JB2",
    "ANL A, #data",
    "CALL (page 2)",
    "STRT T",
    "JT1",
    "DA A",
    "ANL A, R0",
    "ANL A, R1",
    "ANL A, R2",
    "ANL A, R3",
    "ANL A, R4",
    "ANL A, R5",
    "ANL A, R6",
    "ANL A, R7",
    "ADD A, @R0",
    "ADD A, @R1",
    "MOV T, A",
    "ILL",
    "JMP (page 3)",
    "STOP TCNT",
    "ILL",
    "RRC A",
    "ADD A, R0",
    "ADD A, R1",
    "ADD A, R2",
    "ADD A, R3",
    "ADD A, R4",
    "ADD A, R5",
    "ADD A, R6",
    "ADD A, R7",
    "ADDC A, @R0",
    "ADDC A, @R1",
    "JB3",
    "ILL",
    "CALL (page 3)",
    "ENT0 CLK",
    "JF1",
    "RR A",
    "ADDC A, R0",
    "ADDC A, R1",
    "ADDC A, R2",
    "ADDC A, R3",
    "ADDC A, R4",
    "ADDC A, R5",
    "ADDC A, R6",
    "ADDC A, R7",
    "MOVX A, @R0",
    "MOVX A, @R1",
    "ILL",
    "RET",
    "JMP (page 4)",
    "CLR F0",
    "JNI",
    "ILL",
    "ORL BUS, #data",
    "ORL P1, #data",
    "ORL P2, #data",
    "ILL",
    "ORLD P4, A",
    "ORLD P5, A",
    "ORLD P6, A",
    "ORLD P7, A",
    "MOVX @R0, A",
    "MOVX @R1, A",
    "JB4",
    "RETR",
    "CALL (page 4)",
    "CPL F0",
    "JNZ",
    "CLR C",
    "ANL BUS, #data",
    "ANL P1, #data",
    "ANL P2, #data",
    "ILL",
    "ANLD P4, A",
    "ANLD P5, A",
    "ANLD P6, A",
    "ANLD P7, A",
    "MOV @R0, A",
    "MOV @R1, A",
    "ILL",
    "MOVP A, @A",
    "JMP (page 5)",
    "CLR F1",
    "ILL",
    "CPL C",
    "MOV R0, A",
    "MOV R1, A",
    "MOV R2, A",
    "MOV R3, A",
    "MOV R4, A",
    "MOV R5, A",
    "MOV R6, A",
    "MOV R7, A",
    "MOV @R0, #data",
    "MOV @R1, #data",
    "JB5",
    "JMPP @A",
    "CALL (page 5)",
    "CPL F1",
    "JF0",
    "ILL",
    "MOV R0, #data",
    "MOV R1, #data",
    "MOV R2, #data",
    "MOV R3, #data",
    "MOV R4, #data",
    "MOV R5, #data",
    "MOV R6, #data",
    "MOV R7, #data",
    "ILL",
    "ILL",
    "ILL",
    "ILL",
    "JMP (page 6)",
    "SEL RB0",
    "JZ",
    "MOV A, PSW",
    "DEC R0",
    "DEC R1",
    "DEC R2",
    "DEC R3",
    "DEC R4",
    "DEC R5",
    "DEC R6",
    "DEC R7",
    "XRL A, @R0",
    "XRL A, @R1",
    "JB6",
    "XRL A, ",
    "CALL (page 6)",
    "SEL RB1",
    "ILL",
    "MOV PSW, A",
    "XRL A, R0",
    "XRL A, R1",
    "XRL A, R2",
    "XRL A, R3",
    "XRL A, R4",
    "XRL A, R5",
    "XRL A, R6",
    "XRL A, R7",
    "ILL",
    "ILL",
    "ILL",
    "MOVP3 A, @A",
    "JMP (page 7)",
    "SEL MB0",
    "JNC",
    "RL A",
    "DJNZ R0",
    "DJNZ R1",
    "DJNZ R2",
    "DJNZ R3",
    "DJNZ R4",
    "DJNZ R5",
    "DJNZ R6",
    "DJNZ R7",
    "MOV A, @R0",
    "MOV A, @R1",
    "JB7",
    "ILL",
    "CALL (page 7)",
    "SEL MB1",
    "JC",
    "RLC A",
    "MOV A, R0",
    "MOV A, R1",
    "MOV A, R2",
    "MOV A, R3",
    "MOV A, R4",
    "MOV A, R5",
    "MOV A, R6",
    "MOV A, R7"
};

#endif
